# Generated by Django 4.1.7 on 2023-02-21 05:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("banks", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="pnb",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Date", models.DateField(default=datetime.date.today)),
                ("Description", models.CharField(max_length=50)),
                ("Withdrawal", models.CharField(max_length=10)),
                ("Deposit", models.CharField(max_length=10)),
                ("Balance", models.CharField(max_length=10)),
            ],
        ),
        migrations.RenameModel(
            old_name="TableForm",
            new_name="hdfc",
        ),
    ]
